image:
  file: Dockerfile
ports:
  - port: 8080
  - port: 3306
    onOpen: ignore
checkoutLocation: "lamp-example"
workspaceLocation: "."
tasks:
  - name: MySQL
    command: >
        mysqld --initialize-insecure;
        mysqld;
  - name: Apache
    command: >
        apachectl start;
  - name: WordPress
    command: >
        wp core download
        wp config create --dbname=wpclidemo --dbuser=root
        wp db create
        wp core install --url=$(gp url 3000) --title="WP-Gitpod" --admin_user=gitpod --admin_password=gitpod --admin_email=nacho@4geeks.co
