image:
  file: Dockerfile
ports:
  - port: 8080
  - port: 3306
    onOpen: ignore
checkoutLocation: "lamp-example"
workspaceLocation: "."
tasks:
  - name: MySQL
    command: >
        mysqld --initialize-insecure;
        mysqld;
  - name: Apache
    command: >
        apachectl start;
  - name: Wordpress
    before: MySQL
    command: >
        wp core download --path=$GITPOD_REPO_ROOT
        chmod 660 $GITPOD_REPO_ROOT/.htaccess;
        cd $GITPOD_REPO_ROOT;
        wp config create --dbname=wpclidemo --dbuser=root --dbpass=;
        wp db create;
        wp core install --url=$(gp url 8080) --title="WP-Gitpod" --admin_user=gitpod --admin_password=gitpod --admin_email=nacho@4geeks.co;
