image:
  file: Dockerfile
ports:
  - port: 8080
  - port: 3306
    onOpen: ignore
checkoutLocation: "wordpress"
workspaceLocation: "."
tasks:
  - name: MySQL
    init: wp core download --path=$GITPOD_REPO_ROOT;
    command: >
        mysqld --initialize-insecure;
        mysqld &
        sleep 5;
        cd $GITPOD_REPO_ROOT;
        wp config create --dbname=wpclidemo --dbuser=root;
  - name: Apache
    command: >
        apachectl start;
  - name: WordPress
    command: >
        chmod 660 $GITPOD_REPO_ROOT/.htaccess;
        cd $GITPOD_REPO_ROOT;
